console.log('Current Working Directory Is ' + process.cwd());
process.chdir("assets");
console.log('Current Working Directory Is ' + process.cwd());
process.chdir("js");
console.log('Current Working Directory Is ' + process.cwd());
process.chdir("../");
console.log('Current Working Directory Is ' + process.cwd());
process.chdir("../");
console.log('Current Working Directory Is ' + process.cwd());
process.chdir("../");
console.log('Current Working Directory Is ' + process.cwd());
process.chdir("../");
console.log('Current Working Directory Is ' + process.cwd());
process.chdir("../");
console.log('Current Working Directory Is ' + process.cwd());
process.chdir("../");
console.log('Current Working Directory Is ' + process.cwd());
console.log('Node Executable File Is At ' + process.execPath);
console.log('Contents Of PATH Variable are ' + process.env.PATH);
console.log('');
console.log('Contents Of PATH Variable are ...');
console.log(process.env.PATH.split(';').forEach(function(dir){console.log(dir);}));
